// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiDbConnector.Context;

#nullable disable

namespace WebApiDbConnector.Migrations
{
    [DbContext(typeof(TripsContext))]
    partial class TripsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiDbConnector.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("character(100)")
                        .HasColumnName("company_name")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("company_pkey");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .HasMaxLength(30)
                        .HasColumnType("character(30)")
                        .HasColumnName("firstname")
                        .IsFixedLength();

                    b.Property<string>("Lastname")
                        .HasMaxLength(30)
                        .HasColumnType("character(30)")
                        .HasColumnName("lastname")
                        .IsFixedLength();

                    b.Property<string>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("character(30)")
                        .HasColumnName("patronymic")
                        .IsFixedLength();

                    b.Property<int?>("telegram_id")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id")
                        .HasName("employes_pkey");

                    b.ToTable("employes", (string)null);
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .HasMaxLength(30)
                        .HasColumnType("character(30)")
                        .HasColumnName("firstname")
                        .IsFixedLength();

                    b.Property<string>("Lastname")
                        .HasMaxLength(30)
                        .HasColumnType("character(30)")
                        .HasColumnName("lastname")
                        .IsFixedLength();

                    b.Property<string>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("character(30)")
                        .HasColumnName("patronymic")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("managers_pkey");

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character(500)")
                        .HasColumnName("caption")
                        .IsFixedLength();

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("contract_date");

                    b.Property<string>("Customer")
                        .HasMaxLength(200)
                        .HasColumnType("character(200)")
                        .HasColumnName("customer")
                        .IsFixedLength();

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character(200)")
                        .HasColumnName("customer_address")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeadlineContract")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deadline_contract");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("employe_id");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<DateTime?>("TripDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("trip_date");

                    b.Property<int?>("TripTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_type_id");

                    b.HasKey("Id")
                        .HasName("trips_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TripTypeId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Triptype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Typecontract")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .HasColumnName("typecontract")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("triptype_pkey");

                    b.ToTable("triptype", (string)null);
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Trip", b =>
                {
                    b.HasOne("WebApiDbConnector.Models.Company", "Company")
                        .WithMany("Trips")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("trips_company_id_fkey");

                    b.HasOne("WebApiDbConnector.Models.Employe", "Employe")
                        .WithMany("Trips")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("trips_employe_id_fkey");

                    b.HasOne("WebApiDbConnector.Models.Manager", "Manager")
                        .WithMany("Trips")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("trips_manager_id_fkey");

                    b.HasOne("WebApiDbConnector.Models.Triptype", "TripType")
                        .WithMany("Trips")
                        .HasForeignKey("TripTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("trips_trip_type_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("Employe");

                    b.Navigation("Manager");

                    b.Navigation("TripType");
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Company", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Employe", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Manager", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WebApiDbConnector.Models.Triptype", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
